### ISSUE TITLE
The code for quick start is not working

### ISSUE THREAD

**Issue by teljotom** [blackberry/bb-spark-javascript-samples#2]
hi,
please tell me the full guide to set up the quick start functionality.

I think I made mistakes on configuring the config.js file.  so please guide me to set up the config.js 

thanks in advnzzz..

**Comment by JeffinWithYa** [comment]
Hi,

Assuming you are Google sign-ins to build this sample, you'll only need 3 pieces of info to fill out the config.js file:

1. ID_PROVIDER_DOMAIN will come from your organization portal at [account.good.com](account.good.com). If you do not have a domain for your application, you can request one by creating a BBM Enterprise SDK application through the portal.
2. Change your AUTH_CONFIGURATION to one of 'OAuth' or 'JWT'. For Google sign-ins, use 'OAuth'.
3. Your 'clientID' and 'redirectUri' will come from your application on Google's developer console. Head to console.developers.google.com, select your application, then 'Web client' under your OAuth 2.0 client IDs.

For more information, you can check out our [getting started guide](https://developer.blackberry.com/files/bbm-enterprise/documents/guide/html/examples/javascript/QuickStart/README.html). If you have any further questions, please email our SDK support team at bbmesdksupport@blackberry.com
